-- Regression test per la migration 020 (issue #90).
--
--   bash supabase/tests/run-migration-tests.sh

\set ON_ERROR_STOP on

\ir fixtures/production_shape.sql

-- La 018 e' un PRESUPPOSTO, non un dettaglio: e' li' che nasce l'indice
-- univoco su `vis_referee_no`, cioe' l'identita' vera. L'asserzione B2
-- verifica che la 020 tolga il vincolo sbagliato senza portarsi via quello
-- giusto, e senza questa riga non avrebbe nulla da verificare.
\ir ../migrations/018_restore_match_referees.sql

-- La produzione ha questo vincolo; il fixture no, perche' e' ricostruito dai
-- tipi e non dai vincoli. Lo si aggiunge qui per riprodurre esattamente lo
-- stato che ha fatto cadere il primo backfill reale.
ALTER TABLE public.referees
  ADD CONSTRAINT referees_referee_id_unique UNIQUE (referee_id);

-- E la produzione ha anche cio' che si APPOGGIA a quel vincolo: una FK che
-- identifica un arbitro per nome. E' cio' che ha fatto fallire il primo
-- tentativo di applicare la 020 (2BP01). Senza questa tabella il test
-- verificherebbe una migration piu' facile di quella vera.
CREATE TABLE IF NOT EXISTS public.referee_analytics (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referee_id  VARCHAR REFERENCES public.referees(referee_id),
  date        DATE NOT NULL,
  UNIQUE (referee_id, date)
);

-- =============================================================================
-- PARTE A: il guasto, riprodotto
-- =============================================================================

DO $$
BEGIN
  BEGIN
    -- Due PERSONE DIVERSE (vis_referee_no diversi) con lo stesso nome. E'
    -- esattamente cio' che il VIS ha restituito il 2026-08-02: "Mary Kerekere".
    INSERT INTO public.referees (vis_referee_no, referee_id)
    VALUES ('900001', 'Mary Kerekere');
    INSERT INTO public.referees (vis_referee_no, referee_id)
    VALUES ('900002', 'Mary Kerekere');
    RAISE EXCEPTION 'A1 FALLITO: il fixture non riproduce il vincolo, il resto '
                    'del file passerebbe a vuoto';
  EXCEPTION WHEN unique_violation THEN
    RAISE NOTICE 'A1 ok: prima della 020 due omonimi non possono coesistere';
  END;
END $$;

\ir ../migrations/020_referees_name_is_not_an_identity.sql

-- =============================================================================
-- PARTE B: dopo la 020
-- =============================================================================

DO $$
DECLARE
  n INT;
BEGIN
  INSERT INTO public.referees (vis_referee_no, referee_id)
  VALUES ('900001', 'Mary Kerekere'), ('900002', 'Mary Kerekere');

  SELECT count(*) INTO n FROM public.referees WHERE referee_id = 'Mary Kerekere';
  IF n <> 2 THEN
    RAISE EXCEPTION 'B1 FALLITO: % omonimi memorizzati, attesi 2', n;
  END IF;
  RAISE NOTICE 'B1 ok: due arbitri diversi possono chiamarsi allo stesso modo';
END $$;

-- B2: cio' che RESTA vero. L'identita' e' `vis_referee_no`, e la 018 la
-- protegge: rimuovere il vincolo sbagliato non deve aver rimosso quello giusto.
DO $$
BEGIN
  BEGIN
    INSERT INTO public.referees (vis_referee_no, referee_id)
    VALUES ('900001', 'Un Altro Nome');
    RAISE EXCEPTION 'B2 FALLITO: vis_referee_no duplicato accettato — il worker '
                    'creerebbe due identita'' per lo stesso arbitro';
  EXCEPTION WHEN unique_violation THEN
    RAISE NOTICE 'B2 ok: vis_referee_no resta univoco, ed e'' l''identita''';
  END;
END $$;

-- B4: la dipendenza e' stata sciolta, e i suoi dati NON sono stati portati via.
-- La 020 toglie una FK; se avesse usato `DROP ... CASCADE` questa tabella
-- potrebbe non esistere piu'.
DO $$
DECLARE
  fks INT;
  righe INT;
BEGIN
  SELECT count(*) INTO fks
    FROM pg_constraint c
    JOIN pg_class rt ON rt.oid = c.confrelid
   WHERE c.contype = 'f' AND rt.relname = 'referees'
     AND (SELECT array_agg(a.attname::text ORDER BY a.attname)
            FROM unnest(c.confkey) AS k(attnum)
            JOIN pg_attribute a ON a.attrelid = c.confrelid AND a.attnum = k.attnum)
         = ARRAY['referee_id'];
  IF fks <> 0 THEN
    RAISE EXCEPTION 'B4 FALLITO: % FK puntano ancora al nome', fks;
  END IF;

  SELECT count(*) INTO righe FROM public.referee_analytics;
  RAISE NOTICE 'B4 ok: nessuna FK verso il nome, referee_analytics ancora li'' '
               '(% righe)', righe;
END $$;

-- B3: e i nomi non sono stati persi lungo la strada.
DO $$
DECLARE
  n INT;
BEGIN
  SELECT count(*) INTO n FROM public.referees WHERE referee_id IS NOT NULL;
  IF n < 5 THEN
    RAISE EXCEPTION 'B3 FALLITO: solo % righe hanno ancora un nome', n;
  END IF;
  RAISE NOTICE 'B3 ok: % nomi intatti — la 020 toglie un vincolo, non dati', n;
END $$;

-- =============================================================================
-- PARTE C: idempotenza
-- =============================================================================

\ir ../migrations/020_referees_name_is_not_an_identity.sql

DO $$
DECLARE
  v INT;
BEGIN
  SELECT count(*) INTO v FROM public.schema_versions WHERE version = '4.2.1';
  IF v <> 1 THEN
    RAISE EXCEPTION 'C1 FALLITO: schema_versions ha % righe per 4.2.1', v;
  END IF;
  RAISE NOTICE 'C1 ok: riapplicare la 020 non cambia nulla';
END $$;

\echo ''
\echo '================================================================'
\echo ' migration 020 (issue #90): TUTTE LE ASSERZIONI OK'
\echo '================================================================'
