-- Regression test for migration 017 (issue #77).
--
-- Runs against a throwaway PostgreSQL, never against the project. It rebuilds a
-- faithful miniature of production — the Supabase API roles, the Supabase
-- default grants, and the exact policies migrations 004/007/009/011/016 left
-- behind — then asserts two things:
--
--   PART A: what the *old* state really allowed, and why the issue #77 counts
--           over-report. This part is the evidence behind `supabase/RLS.md`.
--   PART B: after 017, `anon` is denied on every verb of every table, with an
--           explicit error rather than a silent empty result.
--
-- How to run (from the repository root):
--
--   docker run -d --name beachref-rls-test -e POSTGRES_PASSWORD=postgres \
--     -v "$PWD/supabase:/repo/supabase" postgres:15
--   docker exec beachref-rls-test psql -U postgres -v ON_ERROR_STOP=1 \
--     -f /repo/supabase/tests/rls_deny_all.test.sql
--   docker rm -f beachref-rls-test
--
-- It must be run with `-f` (not piped on stdin) because it includes the
-- migration with `\ir`, which resolves relative to this file.

\set ON_ERROR_STOP on

-- =============================================================================
-- FIXTURE: the Supabase roles and their default grants
-- =============================================================================

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN NOINHERIT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN NOINHERIT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    CREATE ROLE service_role NOLOGIN NOINHERIT BYPASSRLS;
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;

-- The production tables this issue turns on, trimmed to the shape that matters:
-- primary key type, one NOT NULL column, the columns the probe touches.

CREATE TABLE public.tournaments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vis_tournament_no VARCHAR NOT NULL,
  name VARCHAR
);

CREATE TABLE public.matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vis_match_no BIGINT NOT NULL,
  status TEXT
);

CREATE TABLE public.sync_error_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  error_message TEXT
);

-- sync_status as production actually has it: primary key `entity_type`, and no
-- `id` column at all. Migrations 009 and 010 both redefine it *with* an
-- `id bigint`; production kept the 002.5 shape. That divergence is what
-- produced the two PGRST204 results in issue #77 (AC4).
CREATE TABLE public.sync_status (
  entity_type VARCHAR PRIMARY KEY,
  last_sync TIMESTAMP
);

-- A table nobody ever wrote an anon policy for, used to show what a genuine
-- RLS denial looks like from the client's side.
CREATE TABLE public.notification_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payload TEXT
);

GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;

-- --- the policies as the migration history left them -------------------------

ALTER TABLE public.tournaments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_read" ON public.tournaments FOR SELECT USING (true);           -- 007/011
-- Production has no INSERT policy restricting `tournaments`, even though
-- migration 007 declares `service_upsert`. Reproduced as production behaves,
-- which is what the probe measured.
CREATE POLICY "anon_insert" ON public.tournaments FOR INSERT WITH CHECK (true);

ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_read" ON public.matches FOR SELECT USING (true);               -- 008/011
CREATE POLICY "matches_service_insert" ON public.matches                           -- 016 §3a
  FOR INSERT WITH CHECK (current_setting('request.jwt.claim.role', true) = 'service_role');
CREATE POLICY "matches_service_update" ON public.matches                           -- 016 §3b
  FOR UPDATE USING (current_setting('request.jwt.claim.role', true) = 'service_role');
-- and, as in production, no DELETE policy at all.

ALTER TABLE public.sync_error_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow monitoring read" ON public.sync_error_log                     -- 004, kept by 016
  FOR SELECT USING (true);

ALTER TABLE public.sync_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_read" ON public.sync_status FOR SELECT USING (true);           -- 001/002/009

ALTER TABLE public.notification_logs ENABLE ROW LEVEL SECURITY;                    -- no anon policy

INSERT INTO public.tournaments (vis_tournament_no, name) VALUES ('T1', 'Cervia');
INSERT INTO public.matches (vis_match_no, status) VALUES (1, 'Scheduled');
INSERT INTO public.sync_error_log (error_message) VALUES ('connection refused to internal host');
INSERT INTO public.sync_status (entity_type) VALUES ('tournaments');
INSERT INTO public.notification_logs (payload) VALUES ('device token');

-- =============================================================================
-- PART A — what the old state really allowed
-- =============================================================================

SET ROLE anon;

-- A1. The reads that are genuinely open are genuinely open. These are the real
--     findings of issue #77.
DO $$
DECLARE n INT;
BEGIN
  SELECT count(*) INTO n FROM public.sync_error_log;
  ASSERT n = 1, 'A1: sync_error_log should be readable by anon before 017';
  SELECT count(*) INTO n FROM public.sync_status;
  ASSERT n = 1, 'A1: sync_status should be readable by anon before 017';
  RAISE NOTICE 'A1 ok — internal tables were readable by anon (a real finding)';
END $$;

-- A2. A DELETE that matches no row SUCCEEDS even though no policy permits
--     DELETE at all. RLS filters rows on UPDATE/DELETE; it does not raise. That
--     is why `verify:rls` reported 17 "writable" tables: it probed with
--     `.eq('id', <impossible id>)`, which can never match, so "accepted" was
--     inevitable whatever the policy said.
DO $$
BEGIN
  DELETE FROM public.matches WHERE id = -1;   -- no DELETE policy exists
  ASSERT FOUND = false, 'A2: the probe must match zero rows';
  RAISE NOTICE 'A2 ok — a zero-row DELETE succeeds with no DELETE policy: "accepted" proves nothing';
END $$;

-- A3. The same DELETE against a row that DOES exist is silently a no-op, not an
--     error. The old state was therefore not exploitable for deletes on
--     `matches` — but nothing in the probe output said so either way.
DO $$
DECLARE n INT;
BEGIN
  DELETE FROM public.matches WHERE id = 1;
  SELECT count(*) INTO n FROM public.matches WHERE id = 1;
  ASSERT n = 1, 'A3: the row must survive — RLS filtered the DELETE';
  RAISE NOTICE 'A3 ok — DELETE on a real row was already denied, silently';
END $$;

-- A4. A SELECT denied by RLS returns an empty set, not an error. So the probe's
--     "readable, no rows returned" is indistinguishable from "denied": the
--     seven such rows in issue #77 were inconclusive, not findings.
DO $$
DECLARE n INT;
BEGIN
  SELECT count(*) INTO n FROM public.notification_logs;   -- one row exists
  ASSERT n = 0, 'A4: RLS must hide the row';
  RAISE NOTICE 'A4 ok — an RLS-filtered SELECT is an empty set, never an error';
END $$;

-- A5. RLS WITH CHECK is evaluated BEFORE the NOT NULL constraints. That is what
--     makes the `tournaments` result a real finding and not an artefact: an
--     empty INSERT into `matches` is rejected with 42501 (RLS) even though
--     `vis_match_no` is NOT NULL, whereas the same INSERT into `tournaments`
--     gets as far as 23502 — meaning the policy let it through.
DO $$
DECLARE code TEXT;
BEGIN
  BEGIN
    INSERT INTO public.matches DEFAULT VALUES;
    ASSERT false, 'A5: the insert into matches should have failed';
  EXCEPTION WHEN OTHERS THEN
    code := SQLSTATE;
  END;
  ASSERT code = '42501',
    format('A5: expected 42501 (RLS) from matches, got %s — the ordering assumption is wrong', code);

  BEGIN
    INSERT INTO public.tournaments DEFAULT VALUES;
    ASSERT false, 'A5: the insert into tournaments should have failed';
  EXCEPTION WHEN OTHERS THEN
    code := SQLSTATE;
  END;
  ASSERT code = '23502',
    format('A5: expected 23502 (not-null) from tournaments, got %s', code);

  RAISE NOTICE 'A5 ok — RLS runs before NOT NULL, so 23502 on tournaments means the policy passed';
END $$;

RESET ROLE;

-- =============================================================================
-- PART B — after migration 017
-- =============================================================================

\ir ../migrations/017_deny_all_public_api_roles.sql

SET ROLE anon;

DO $$
DECLARE
  tables TEXT[] := ARRAY['tournaments', 'matches', 'sync_error_log', 'sync_status', 'notification_logs'];
  cols   TEXT[] := ARRAY['name',        'status',  'error_message',  'entity_type', 'payload'];
  i INT;
  code TEXT;
BEGIN
  FOR i IN 1 .. array_length(tables, 1) LOOP
    code := NULL;
    BEGIN
      EXECUTE format('SELECT 1 FROM public.%I LIMIT 1', tables[i]);
      ASSERT false, format('B: SELECT on %s should be denied', tables[i]);
    EXCEPTION WHEN OTHERS THEN code := SQLSTATE;
    END;
    ASSERT code = '42501', format('B: SELECT on %s returned %s, expected 42501', tables[i], code);

    code := NULL;
    BEGIN
      EXECUTE format('INSERT INTO public.%I DEFAULT VALUES', tables[i]);
      ASSERT false, format('B: INSERT on %s should be denied', tables[i]);
    EXCEPTION WHEN OTHERS THEN code := SQLSTATE;
    END;
    ASSERT code = '42501', format('B: INSERT on %s returned %s, expected 42501', tables[i], code);

    -- A filter that matches nothing must now error anyway: the denial happens
    -- at the privilege gate, before any row is considered. That is what makes
    -- the verification legible instead of ambiguous.
    code := NULL;
    BEGIN
      EXECUTE format('UPDATE public.%I SET %I = %I WHERE false', tables[i], cols[i], cols[i]);
      ASSERT false, format('B: UPDATE on %s should be denied', tables[i]);
    EXCEPTION WHEN OTHERS THEN code := SQLSTATE;
    END;
    ASSERT code = '42501', format('B: UPDATE on %s returned %s, expected 42501', tables[i], code);

    code := NULL;
    BEGIN
      EXECUTE format('DELETE FROM public.%I WHERE false', tables[i]);
      ASSERT false, format('B: DELETE on %s should be denied', tables[i]);
    EXCEPTION WHEN OTHERS THEN code := SQLSTATE;
    END;
    ASSERT code = '42501', format('B: DELETE on %s returned %s, expected 42501', tables[i], code);
  END LOOP;

  RAISE NOTICE 'B ok — anon is denied on select/insert/update/delete for every table, explicitly';
END $$;

RESET ROLE;

-- The same must hold for `authenticated`: the anon key can mint an
-- authenticated session wherever sign-up is open, so leaving that role open
-- would leave the hole open one step further down.
SET ROLE authenticated;
DO $$
DECLARE code TEXT;
BEGIN
  BEGIN
    PERFORM 1 FROM public.sync_error_log LIMIT 1;
    ASSERT false, 'B: authenticated must be denied too';
  EXCEPTION WHEN OTHERS THEN code := SQLSTATE;
  END;
  ASSERT code = '42501', format('B: authenticated SELECT returned %s, expected 42501', code);
  RAISE NOTICE 'B ok — authenticated is denied as well';
END $$;
RESET ROLE;

-- B2. service_role still works: the sync Edge Functions must not break.
SET ROLE service_role;
DO $$
DECLARE n INT;
BEGIN
  SELECT count(*) INTO n FROM public.matches;
  ASSERT n = 1, 'B2: service_role must still read';
  INSERT INTO public.matches (vis_match_no, status) VALUES (2, 'Running');
  UPDATE public.matches SET status = 'Finished' WHERE vis_match_no = 2;
  DELETE FROM public.matches WHERE vis_match_no = 2;
  RAISE NOTICE 'B2 ok — service_role retains full access';
END $$;
RESET ROLE;

-- B3. A table created after the migration must not be reachable either.
CREATE TABLE public.future_table (id BIGINT PRIMARY KEY, secret TEXT);
SET ROLE anon;
DO $$
DECLARE code TEXT;
BEGIN
  BEGIN
    PERFORM 1 FROM public.future_table LIMIT 1;
    ASSERT false, 'B3: a new table must not be readable by anon';
  EXCEPTION WHEN OTHERS THEN code := SQLSTATE;
  END;
  ASSERT code = '42501', format('B3: expected 42501 on a new table, got %s', code);
  RAISE NOTICE 'B3 ok — default privileges keep future tables closed';
END $$;
RESET ROLE;

-- B4. Re-applying the migration is a no-op, not an error.
\ir ../migrations/017_deny_all_public_api_roles.sql

\echo ''
\echo '================================================'
\echo ' rls_deny_all.test.sql — all assertions passed'
\echo '================================================'
