-- A faithful miniature of the production project, for the migration tests.
--
-- "Faithful" means: the column TYPES are the ones the production database
-- actually has, read from the PostgREST OpenAPI definitions with the
-- service_role key — not the ones the repository's migrations would produce.
-- The two have diverged, and that divergence is the whole subject of issue #89
-- (see the header of migration 018). A fixture built from the migrations would
-- therefore test the wrong database.
--
-- Verified shapes (2026-08-01):
--   matches.id           uuid
--   matches.no           character varying, UNIQUE
--   matches.no_referee1  character varying
--   referees.id          bigint
--   referees.vis_referee_no text, NO unique constraint
--   schema_versions      (version, applied_at, description) — and no `id`
--
-- Kept trimmed to the columns the migration under test touches, plus enough
-- shape to make the assertions meaningful.

\set ON_ERROR_STOP on

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

-- The Supabase API roles.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN NOINHERIT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN NOINHERIT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    CREATE ROLE service_role NOLOGIN NOINHERIT BYPASSRLS;
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

CREATE TABLE public.matches (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  no                       CHARACTER VARYING NOT NULL UNIQUE,
  tournament_no            CHARACTER VARYING NOT NULL,
  local_date               DATE,
  status                   CHARACTER VARYING,
  no_referee1              CHARACTER VARYING,
  no_referee2              CHARACTER VARYING,
  referee1_name            CHARACTER VARYING,
  referee2_name            CHARACTER VARYING,
  created_at               TIMESTAMP DEFAULT now(),
  updated_at               TIMESTAMP DEFAULT now()
);

CREATE TABLE public.referees (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vis_referee_no           TEXT,
  first_name               TEXT,
  last_name                TEXT,
  federation_code          TEXT,
  level                    TEXT,
  gender                   TEXT,
  experience_years         INTEGER,
  status                   TEXT,
  referee_id               CHARACTER VARYING,
  created_at               TIMESTAMPTZ DEFAULT now(),
  updated_at               TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.schema_versions (
  version                  CHARACTER VARYING,
  applied_at               TIMESTAMP DEFAULT now(),
  description              TEXT
);

-- The two leftovers migration 013 created and never cleaned up. Present so the
-- test can assert migration 018 does not touch them.
CREATE TABLE public.match_referees_backup (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id                 TEXT,
  referee_id               INTEGER,
  role                     CHARACTER VARYING
);

CREATE TABLE public.matches_backup (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  no                       CHARACTER VARYING
);

-- Data shaped like what is actually there: referee names in two different
-- conventions, and no_referee1 empty on every row.
INSERT INTO public.matches (no, tournament_no, local_date, status, referee1_name, referee2_name)
VALUES ('499650', '8242', '2025-09-17', '15', 'Lowry Suzanne',  'Vachutka Milan'),
       ('499651', '8242', '2025-09-17', '15', 'Mol Anders',     NULL),
       ('499652', '8242', '2025-09-18', '15', NULL,             NULL);

INSERT INTO public.referees (vis_referee_no, first_name, last_name, federation_code, status, referee_id)
VALUES ('155754', 'Jonathan', 'Lamprecht', 'AUS', 'ACTIVE', 'Jonathan Lamprecht'),
       ('155755', 'Suzanne',  'Lowry',     'USA', 'ACTIVE', 'Suzanne Lowry'),
       ('155756', 'Milan',    'Vachutka',  'CZE', 'ACTIVE', 'Milan Vachutka');

-- Two referees with no VIS number, to prove the partial unique index tolerates
-- repeated NULLs (479 of 480 production rows have one; the 480th does not).
INSERT INTO public.referees (vis_referee_no, first_name, last_name, status)
VALUES (NULL, 'Unknown', 'One', 'ACTIVE'),
       (NULL, 'Unknown', 'Two', 'ACTIVE');
