/**
 * Apply migrations using PostgreSQL client
 */

const { Client } = require('pg');
const fs = require('fs');
const path = require('path');

// Database connection
const client = new Client({
  host: 'db.peofucnjgcrgswzqslpb.supabase.co',
  port: 5432,
  database: 'postgres',
  user: 'postgres',
  password: 'nVpvfuhinmR2s8Ae',
  ssl: { rejectUnauthorized: false }
});

console.log('🚀 Connecting to Supabase PostgreSQL...\n');

async function applyMigrations() {
  try {
    // Connect to database
    await client.connect();
    console.log('✅ Connected to database');

    // First, create schema_versions table if it doesn't exist
    console.log('\n1. Creating schema_versions table...');
    const schemaVersionsSQL = `
      CREATE TABLE IF NOT EXISTS schema_versions (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        version text UNIQUE NOT NULL,
        description text,
        applied_at timestamptz DEFAULT now()
      );
      
      ALTER TABLE schema_versions ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS "anon_read" ON schema_versions;
      CREATE POLICY "anon_read" ON schema_versions FOR SELECT USING (true);
      GRANT ALL ON schema_versions TO service_role;
    `;
    
    await client.query(schemaVersionsSQL);
    console.log('✅ Schema versions table ready');

    // Apply migrations in order
    const migrations = [
      '002_create_database_schema.sql',
      '008_create_match_schema.sql', 
      '009_create_analytics_schema.sql',
      '009_create_sync_status_schema.sql'
    ];

    for (let i = 0; i < migrations.length; i++) {
      const migration = migrations[i];
      const migrationPath = path.join(__dirname, 'supabase', 'migrations', migration);
      
      console.log(`\n${i + 2}. Applying ${migration}...`);
      
      if (!fs.existsSync(migrationPath)) {
        console.log(`❌ Migration file not found: ${migrationPath}`);
        continue;
      }
      
      try {
        const migrationSQL = fs.readFileSync(migrationPath, 'utf8');
        
        // Execute the migration
        await client.query(migrationSQL);
        console.log(`✅ ${migration} applied successfully`);
        
      } catch (error) {
        console.log(`❌ Failed to apply ${migration}:`);
        console.log(`   Error: ${error.message}`);
        
        // If it's a "already exists" error, that's okay
        if (error.message.includes('already exists') || 
            error.message.includes('duplicate key') ||
            error.message.includes('relation') && error.message.includes('already exists')) {
          console.log(`   ⚠️  Migration partially applied (some objects already exist)`);
        } else {
          console.log(`   💥 Critical error - stopping migration process`);
          break;
        }
      }
    }

    // Test if all tables were created
    console.log('\n🔍 Verifying table creation...');
    const tablesQuery = `
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
      AND table_name IN ('tournaments', 'referees', 'events', 'matches', 'match_referees', 
                         'referee_analytics', 'analytics_events', 'sync_status', 'sync_error_log')
      ORDER BY table_name;
    `;
    
    const result = await client.query(tablesQuery);
    console.log('📋 Created tables:');
    result.rows.forEach(row => {
      console.log(`   ✅ ${row.table_name}`);
    });
    
    const expectedTables = ['tournaments', 'referees', 'events', 'matches', 'match_referees', 
                           'referee_analytics', 'analytics_events', 'sync_status', 'sync_error_log'];
    const createdTables = result.rows.map(row => row.table_name);
    const missingTables = expectedTables.filter(table => !createdTables.includes(table));
    
    if (missingTables.length > 0) {
      console.log('\n⚠️  Missing tables:');
      missingTables.forEach(table => {
        console.log(`   ❌ ${table}`);
      });
    } else {
      console.log('\n🎉 All required tables created successfully!');
    }

  } catch (error) {
    console.error('💥 Migration failed:', error.message);
  } finally {
    await client.end();
    console.log('\n🔌 Database connection closed');
  }
}

applyMigrations();