/**
 * Apply all missing Supabase migrations to fix 404 errors
 */

const fs = require('fs');
const path = require('path');

console.log('📋 COMPLETE DATABASE SETUP REQUIRED');
console.log('═══════════════════════════════════════════════════');
console.log('You need to run these migrations in your Supabase Dashboard SQL Editor:');
console.log('🌐 https://supabase.com/dashboard/project/peofucnjgcrgswzqslpb/sql\n');

const migrations = [
  '002_create_database_schema.sql',
  '008_create_match_schema.sql', 
  '009_create_analytics_schema.sql',
  '009_create_sync_status_schema.sql'
];

console.log('Run these migrations IN ORDER:\n');

migrations.forEach((migration, index) => {
  const migrationPath = path.join(__dirname, 'supabase', 'migrations', migration);
  
  console.log(`${index + 1}. ${migration}`);
  console.log(`   File: supabase/migrations/${migration}`);
  
  if (fs.existsSync(migrationPath)) {
    const content = fs.readFileSync(migrationPath, 'utf8');
    const lines = content.split('\n').length;
    console.log(`   ✅ Ready (${lines} lines)`);
  } else {
    console.log(`   ❌ File not found!`);
  }
  console.log('');
});

console.log('INSTRUCTIONS:');
console.log('1. Copy the ENTIRE contents of each migration file');
console.log('2. Paste into Supabase Dashboard SQL Editor');
console.log('3. Click "Run" for each migration');
console.log('4. Run them in the order listed above');
console.log('5. Wait for each to complete before running the next');
console.log('');
console.log('This will create all the missing tables:');
console.log('- tournaments, referees, events, matches');
console.log('- match_referees, referee_analytics, analytics_events');
console.log('- sync_status, sync_error_log');
console.log('- All necessary indexes, triggers, and RLS policies');

// Check if the basic schema version table exists
console.log('\n🔍 First, make sure you have the schema_versions table:');
console.log('If the migrations fail, run this first:\n');

const schemaVersionSQL = `
-- Create schema_versions table if it doesn't exist
CREATE TABLE IF NOT EXISTS schema_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version text UNIQUE NOT NULL,
  description text,
  applied_at timestamptz DEFAULT now()
);

-- Enable RLS and create policies
ALTER TABLE schema_versions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_read" ON schema_versions FOR SELECT USING (true);
GRANT ALL ON schema_versions TO service_role;
`;

console.log(schemaVersionSQL);