-- This migration implements the analytics schema for Story 4.1
-- Creates analytics tables, triggers, and functions for referee performance tracking

-- =============================================================================
-- ANALYTICS SCHEMA CREATION
-- =============================================================================

-- Create referees table if it doesn't exist (referenced by referee_analytics)
CREATE TABLE IF NOT EXISTS referees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vis_referee_no text UNIQUE,
  first_name text,
  last_name text,
  federation_code text,
  level text,
  gender text CHECK (gender IN ('M','F')),
  experience_years int,
  status text CHECK (status IN ('ACTIVE','INACTIVE','SUSPENDED')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create referee_analytics table for aggregated metrics
CREATE TABLE IF NOT EXISTS referee_analytics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referee_id bigint REFERENCES referees(id),
  date date NOT NULL,
  total_assignments int DEFAULT 0,
  first_referee_count int DEFAULT 0,
  second_referee_count int DEFAULT 0,
  challenge_referee_count int DEFAULT 0,
  tournaments_worked text[],
  performance_score decimal(5,2),
  created_at timestamptz DEFAULT now(),
  UNIQUE(referee_id, date)
);

-- Create event tracking table for client-side analytics
CREATE TABLE IF NOT EXISTS analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL, -- 'referee_view', 'assignment_action', 'match_monitor'
  user_context jsonb,
  event_data jsonb,
  timestamp timestamptz DEFAULT now()
);

-- =============================================================================
-- ANALYTICS INDEXES FOR PERFORMANCE
-- =============================================================================

-- Indexes for efficient analytics queries
CREATE INDEX IF NOT EXISTS idx_referee_analytics_referee_id ON referee_analytics (referee_id);
CREATE INDEX IF NOT EXISTS idx_referee_analytics_date ON referee_analytics (date);
CREATE INDEX IF NOT EXISTS idx_referee_analytics_referee_date ON referee_analytics (referee_id, date);

CREATE INDEX IF NOT EXISTS idx_analytics_events_type ON analytics_events (event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_events_timestamp ON analytics_events (timestamp);
CREATE INDEX IF NOT EXISTS idx_analytics_events_type_timestamp ON analytics_events (event_type, timestamp);

-- Referees table indexes
CREATE INDEX IF NOT EXISTS idx_referees_vis_referee_no ON referees (vis_referee_no);
CREATE INDEX IF NOT EXISTS idx_referees_federation_code ON referees (federation_code);
CREATE INDEX IF NOT EXISTS idx_referees_status ON referees (status);

-- =============================================================================
-- ANALYTICS DATA COLLECTION TRIGGERS
-- =============================================================================

-- Function to update referee analytics when match_referees changes
CREATE OR REPLACE FUNCTION update_referee_analytics_on_assignment()
RETURNS TRIGGER AS $$
DECLARE
  ref_id bigint;
  match_date date;
  tournament_codes text[];
BEGIN
  -- Get referee_id and match date from the trigger
  IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
    ref_id := NEW.referee_id;
    -- Get match date from matches table
    SELECT DATE(m.utc_datetime), ARRAY_AGG(DISTINCT m.tournament_code)
    INTO match_date, tournament_codes
    FROM matches m
    WHERE m.id = NEW.match_id
    GROUP BY DATE(m.utc_datetime);
  ELSIF TG_OP = 'DELETE' THEN
    ref_id := OLD.referee_id;
    -- Get match date from matches table
    SELECT DATE(m.utc_datetime), ARRAY_AGG(DISTINCT m.tournament_code)
    INTO match_date, tournament_codes
    FROM matches m
    WHERE m.id = OLD.match_id
    GROUP BY DATE(m.utc_datetime);
  END IF;

  -- Update or create analytics record
  INSERT INTO referee_analytics (referee_id, date, tournaments_worked)
  VALUES (ref_id, match_date, tournament_codes)
  ON CONFLICT (referee_id, date)
  DO UPDATE SET
    tournaments_worked = COALESCE(referee_analytics.tournaments_worked, ARRAY[]::text[]) || COALESCE(tournament_codes, ARRAY[]::text[]),
    updated_at = now();

  -- Recalculate assignment counts for this referee and date
  UPDATE referee_analytics SET
    total_assignments = (
      SELECT COUNT(*)
      FROM match_referees mr
      JOIN matches m ON mr.match_id = m.id
      WHERE mr.referee_id = ref_id AND DATE(m.utc_datetime) = match_date
    ),
    first_referee_count = (
      SELECT COUNT(*)
      FROM match_referees mr
      JOIN matches m ON mr.match_id = m.id
      WHERE mr.referee_id = ref_id AND mr.role = 'FIRST' AND DATE(m.utc_datetime) = match_date
    ),
    second_referee_count = (
      SELECT COUNT(*)
      FROM match_referees mr
      JOIN matches m ON mr.match_id = m.id
      WHERE mr.referee_id = ref_id AND mr.role = 'SECOND' AND DATE(m.utc_datetime) = match_date
    ),
    challenge_referee_count = (
      SELECT COUNT(*)
      FROM match_referees mr
      JOIN matches m ON mr.match_id = m.id
      WHERE mr.referee_id = ref_id AND mr.role = 'CHALLENGE' AND DATE(m.utc_datetime) = match_date
    )
  WHERE referee_id = ref_id AND date = match_date;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger on match_referees table for assignment tracking
DROP TRIGGER IF EXISTS trigger_update_referee_analytics ON match_referees;
CREATE TRIGGER trigger_update_referee_analytics
  AFTER INSERT OR UPDATE OR DELETE ON match_referees
  FOR EACH ROW
  EXECUTE FUNCTION update_referee_analytics_on_assignment();

-- Function to update analytics when matches change
CREATE OR REPLACE FUNCTION update_analytics_on_match_change()
RETURNS TRIGGER AS $$
BEGIN
  -- Insert analytics event for match changes
  INSERT INTO analytics_events (event_type, event_data)
  VALUES (
    'match_update',
    jsonb_build_object(
      'match_id', COALESCE(NEW.id, OLD.id),
      'tournament_code', COALESCE(NEW.tournament_code, OLD.tournament_code),
      'status_change', CASE 
        WHEN TG_OP = 'UPDATE' AND OLD.status != NEW.status THEN 
          jsonb_build_object('from', OLD.status, 'to', NEW.status)
        ELSE NULL
      END,
      'operation', TG_OP
    )
  );

  -- Trigger recalculation of affected referee analytics if match datetime changed
  IF TG_OP = 'UPDATE' AND (OLD.utc_datetime != NEW.utc_datetime OR OLD.tournament_code != NEW.tournament_code) THEN
    -- Update all referee analytics for referees assigned to this match
    UPDATE referee_analytics 
    SET tournaments_worked = (
      SELECT ARRAY_AGG(DISTINCT m.tournament_code)
      FROM match_referees mr
      JOIN matches m ON mr.match_id = m.id
      WHERE mr.referee_id = referee_analytics.referee_id 
        AND DATE(m.utc_datetime) = referee_analytics.date
    )
    WHERE referee_id IN (
      SELECT referee_id FROM match_referees WHERE match_id = NEW.id
    ) AND date = DATE(NEW.utc_datetime);
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger on matches table for performance data collection
DROP TRIGGER IF EXISTS trigger_analytics_match_change ON matches;
CREATE TRIGGER trigger_analytics_match_change
  AFTER INSERT OR UPDATE OR DELETE ON matches
  FOR EACH ROW
  EXECUTE FUNCTION update_analytics_on_match_change();

-- =============================================================================
-- ANALYTICS DATA VALIDATION FUNCTIONS
-- =============================================================================

-- Function to validate analytics data integrity
CREATE OR REPLACE FUNCTION validate_analytics_data()
RETURNS TABLE (
  validation_type text,
  issue_count bigint,
  description text
) AS $$
BEGIN
  -- Check for orphaned referee_analytics records
  RETURN QUERY
  SELECT 
    'orphaned_referee_analytics'::text,
    COUNT(*)::bigint,
    'Referee analytics records with referee_id not found in referees table'::text
  FROM referee_analytics ra
  WHERE NOT EXISTS (SELECT 1 FROM referees r WHERE r.id = ra.referee_id);
  
  -- Check for analytics events without required fields
  RETURN QUERY
  SELECT 
    'invalid_analytics_events'::text,
    COUNT(*)::bigint,
    'Analytics events missing event_type or with invalid event_data'::text
  FROM analytics_events 
  WHERE event_type IS NULL OR event_type = '';
  
  -- Check for negative assignment counts
  RETURN QUERY
  SELECT 
    'negative_assignment_counts'::text,
    COUNT(*)::bigint,
    'Referee analytics with negative assignment counts'::text
  FROM referee_analytics 
  WHERE total_assignments < 0 OR first_referee_count < 0 OR second_referee_count < 0 OR challenge_referee_count < 0;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to cleanup old analytics data based on retention policy
CREATE OR REPLACE FUNCTION cleanup_old_analytics_data()
RETURNS TABLE (
  cleanup_type text,
  records_deleted bigint
) AS $$
DECLARE
  deleted_events bigint;
  deleted_analytics bigint;
BEGIN
  -- Delete analytics events older than 90 days (detailed data retention)
  DELETE FROM analytics_events 
  WHERE timestamp < (now() - INTERVAL '90 days');
  GET DIAGNOSTICS deleted_events = ROW_COUNT;
  
  -- Delete referee analytics older than 2 years (aggregated data retention)
  DELETE FROM referee_analytics 
  WHERE created_at < (now() - INTERVAL '2 years');
  GET DIAGNOSTICS deleted_analytics = ROW_COUNT;
  
  RETURN QUERY VALUES
    ('analytics_events'::text, deleted_events),
    ('referee_analytics'::text, deleted_analytics);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- ROW LEVEL SECURITY POLICIES
-- =============================================================================

-- Enable RLS on analytics tables
ALTER TABLE referees ENABLE ROW LEVEL SECURITY;
ALTER TABLE referee_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

-- Policies for referees table
DROP POLICY IF EXISTS "anon_read" ON referees;
DROP POLICY IF EXISTS "service_manage" ON referees;

CREATE POLICY "anon_read" ON referees
FOR SELECT USING (true);

CREATE POLICY "service_manage" ON referees
FOR ALL USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

-- Policies for referee_analytics table
DROP POLICY IF EXISTS "anon_read" ON referee_analytics;
DROP POLICY IF EXISTS "service_manage" ON referee_analytics;

CREATE POLICY "anon_read" ON referee_analytics
FOR SELECT USING (true);

CREATE POLICY "service_manage" ON referee_analytics
FOR ALL USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

-- Policies for analytics_events table
DROP POLICY IF EXISTS "anon_read" ON analytics_events;
DROP POLICY IF EXISTS "service_manage" ON analytics_events;

CREATE POLICY "anon_read" ON analytics_events
FOR SELECT USING (true);

CREATE POLICY "service_manage" ON analytics_events
FOR ALL USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

-- =============================================================================
-- GRANT PERMISSIONS
-- =============================================================================

-- Grant execute permissions to service role
GRANT EXECUTE ON FUNCTION update_referee_analytics_on_assignment() TO service_role;
GRANT EXECUTE ON FUNCTION update_analytics_on_match_change() TO service_role;
GRANT EXECUTE ON FUNCTION validate_analytics_data() TO service_role;
GRANT EXECUTE ON FUNCTION cleanup_old_analytics_data() TO service_role;

-- Grant table permissions
GRANT ALL ON referees TO service_role;
GRANT ALL ON referee_analytics TO service_role;
GRANT ALL ON analytics_events TO service_role;

-- =============================================================================
-- REAL-TIME CONFIGURATION
-- =============================================================================

-- Enable real-time subscriptions for analytics tables
DO $$
BEGIN
  -- Add analytics tables to real-time publication
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE referee_analytics;
    ALTER PUBLICATION supabase_realtime ADD TABLE analytics_events;
    ALTER PUBLICATION supabase_realtime ADD TABLE referees;
  END IF;
EXCEPTION
  WHEN duplicate_object THEN
    -- Tables already added to real-time publication, ignore error
    NULL;
END $$;

-- =============================================================================
-- SCHEMA VERSION UPDATE
-- =============================================================================

INSERT INTO schema_versions (version, description) VALUES
('4.1.0', 'Analytics schema with referee_analytics, analytics_events tables and data collection triggers')
ON CONFLICT (version) DO NOTHING;

-- =============================================================================
-- VALIDATION QUERIES
-- =============================================================================

DO $$
BEGIN
  -- Validate schema creation
  ASSERT (SELECT COUNT(*) FROM information_schema.tables 
          WHERE table_name = 'referee_analytics') = 1,
          'Referee_analytics table was not created';
          
  ASSERT (SELECT COUNT(*) FROM information_schema.tables 
          WHERE table_name = 'analytics_events') = 1,
          'Analytics_events table was not created';
          
  ASSERT (SELECT COUNT(*) FROM information_schema.tables 
          WHERE table_name = 'referees') = 1,
          'Referees table was not created';

  -- Validate functions were created
  ASSERT (SELECT COUNT(*) FROM pg_proc 
          WHERE proname = 'update_referee_analytics_on_assignment') = 1,
          'update_referee_analytics_on_assignment function was not created';
          
  ASSERT (SELECT COUNT(*) FROM pg_proc 
          WHERE proname = 'validate_analytics_data') = 1,
          'validate_analytics_data function was not created';
          
  ASSERT (SELECT COUNT(*) FROM pg_proc 
          WHERE proname = 'cleanup_old_analytics_data') = 1,
          'cleanup_old_analytics_data function was not created';

  -- Validate triggers were created
  ASSERT (SELECT COUNT(*) FROM pg_trigger 
          WHERE tgname = 'trigger_update_referee_analytics') = 1,
          'trigger_update_referee_analytics was not created';
          
  ASSERT (SELECT COUNT(*) FROM pg_trigger 
          WHERE tgname = 'trigger_analytics_match_change') = 1,
          'trigger_analytics_match_change was not created';

  RAISE NOTICE 'Analytics schema migration completed successfully';
END $$;