-- Migration 008: Create Match Schema (Events, Matches, Match-Referees)
-- This migration implements the match schema as specified in Story 2.2
-- Creates events, matches, and match_referees tables with proper relationships

-- =============================================================================
-- EVENTS TABLE SCHEMA
-- =============================================================================

-- Create events table with tournament relationship and VIS compatibility
CREATE TABLE IF NOT EXISTS events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vis_event_no bigint NOT NULL,
  event_code text,
  tournament_id bigint NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
  gender text CHECK (gender IN ('M','W')),
  phase text,                    -- Qualification, Main Draw, Finals
  name text,
  country text,
  start_date date,
  end_date date,
  status text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (tournament_id, gender, phase)
);

-- Create index for events table
CREATE INDEX idx_events_tournament_phase ON events (tournament_id, phase);
CREATE INDEX idx_events_vis_event_no ON events (vis_event_no);
CREATE INDEX idx_events_status ON events (status);

-- =============================================================================
-- MATCHES TABLE SCHEMA
-- =============================================================================

-- Create matches table with proper normalization for sets and team data
CREATE TABLE IF NOT EXISTS matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vis_match_no bigint NOT NULL UNIQUE,
  tournament_code text NOT NULL,            -- VIS: TournamentCode (lookup veloce)
  event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  round_code text,
  round_name text,
  round_phase text,
  utc_datetime timestamptz,
  local_datetime timestamptz,
  court text,
  team_a_name text,
  team_b_name text,
  team_a_fed text,
  team_b_fed text,
  team_a_players bigint[],
  team_b_players bigint[],
  sets jsonb DEFAULT '[]',                  -- [{a:21,b:19}, ...]
  result jsonb,                             -- {resultType, winnerRank, ...}
  status text,
  are_court_and_time_published boolean,
  nb_live_score_upload int,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create indexes for matches table
CREATE INDEX idx_matches_event_id ON matches (event_id);
CREATE INDEX idx_matches_tournament_code ON matches (tournament_code);
CREATE INDEX idx_matches_status ON matches (status);
CREATE INDEX idx_matches_vis_match_no ON matches (vis_match_no);
CREATE INDEX idx_matches_event_status ON matches (event_id, status);
CREATE INDEX idx_matches_utc_datetime ON matches (utc_datetime);

-- =============================================================================
-- MATCH-REFEREES JUNCTION TABLE SCHEMA
-- =============================================================================

-- Create match_referees junction table for referee assignments
CREATE TABLE IF NOT EXISTS match_referees (
  match_id bigint REFERENCES matches(id) ON DELETE CASCADE,
  referee_id bigint REFERENCES referees(id) ON DELETE RESTRICT,
  role text CHECK (role IN ('FIRST','SECOND','CHALLENGE')),
  PRIMARY KEY (match_id, role)
);

-- Create indexes for match_referees table
CREATE INDEX idx_match_referees_referee_id ON match_referees (referee_id);
CREATE INDEX idx_match_referees_match_id ON match_referees (match_id);

-- =============================================================================
-- AUTOMATIC TIMESTAMP TRIGGERS
-- =============================================================================

-- Create timestamp update function for events
CREATE OR REPLACE FUNCTION update_events_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create timestamp update function for matches
CREATE OR REPLACE FUNCTION update_matches_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers for automatic timestamp updates
DROP TRIGGER IF EXISTS update_events_timestamp_trigger ON events;
CREATE TRIGGER update_events_timestamp_trigger
  BEFORE UPDATE ON events
  FOR EACH ROW
  EXECUTE FUNCTION update_events_timestamp();

DROP TRIGGER IF EXISTS update_matches_timestamp_trigger ON matches;
CREATE TRIGGER update_matches_timestamp_trigger
  BEFORE UPDATE ON matches
  FOR EACH ROW
  EXECUTE FUNCTION update_matches_timestamp();

-- =============================================================================
-- ROW LEVEL SECURITY POLICIES
-- =============================================================================

-- Enable RLS on events table
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "anon_read" ON events;
DROP POLICY IF EXISTS "service_upsert" ON events;
DROP POLICY IF EXISTS "service_update" ON events;
DROP POLICY IF EXISTS "service_delete" ON events;

-- Create RLS policies for events
CREATE POLICY "anon_read" ON events
FOR SELECT USING (true);

CREATE POLICY "service_upsert" ON events
FOR INSERT WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "service_update" ON events
FOR UPDATE USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "service_delete" ON events
FOR DELETE USING (auth.role() = 'service_role');

-- Enable RLS on matches table
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "anon_read" ON matches;
DROP POLICY IF EXISTS "service_upsert" ON matches;
DROP POLICY IF EXISTS "service_update" ON matches;
DROP POLICY IF EXISTS "service_delete" ON matches;

-- Create RLS policies for matches
CREATE POLICY "anon_read" ON matches
FOR SELECT USING (true);

CREATE POLICY "service_upsert" ON matches
FOR INSERT WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "service_update" ON matches
FOR UPDATE USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "service_delete" ON matches
FOR DELETE USING (auth.role() = 'service_role');

-- Enable RLS on match_referees table
ALTER TABLE match_referees ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "anon_read" ON match_referees;
DROP POLICY IF EXISTS "service_upsert" ON match_referees;
DROP POLICY IF EXISTS "service_update" ON match_referees;
DROP POLICY IF EXISTS "service_delete" ON match_referees;

-- Create RLS policies for match_referees
CREATE POLICY "anon_read" ON match_referees
FOR SELECT USING (true);

CREATE POLICY "service_upsert" ON match_referees
FOR INSERT WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "service_update" ON match_referees
FOR UPDATE USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "service_delete" ON match_referees
FOR DELETE USING (auth.role() = 'service_role');

-- =============================================================================
-- DATABASE FUNCTIONS FOR MATCH AGGREGATIONS
-- =============================================================================

-- Function for match statistics by tournament
CREATE OR REPLACE FUNCTION get_match_statistics_by_tournament(tournament_code_param text)
RETURNS TABLE (
  total_matches bigint,
  completed_matches bigint,
  active_matches bigint,
  upcoming_matches bigint,
  completion_rate numeric
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*)::bigint as total_matches,
    COUNT(CASE WHEN m.status = 'completed' THEN 1 END)::bigint as completed_matches,
    COUNT(CASE WHEN m.status = 'active' THEN 1 END)::bigint as active_matches,
    COUNT(CASE WHEN m.status = 'upcoming' THEN 1 END)::bigint as upcoming_matches,
    CASE 
      WHEN COUNT(*) > 0 THEN 
        ROUND(COUNT(CASE WHEN m.status = 'completed' THEN 1 END) * 100.0 / COUNT(*), 2)
      ELSE 0
    END as completion_rate
  FROM matches m
  WHERE m.tournament_code = tournament_code_param;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function for referee assignment counts
CREATE OR REPLACE FUNCTION get_referee_assignment_counts(referee_id_param bigint)
RETURNS TABLE (
  total_assignments bigint,
  first_referee_count bigint,
  second_referee_count bigint,
  challenge_referee_count bigint
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*)::bigint as total_assignments,
    COUNT(CASE WHEN mr.role = 'FIRST' THEN 1 END)::bigint as first_referee_count,
    COUNT(CASE WHEN mr.role = 'SECOND' THEN 1 END)::bigint as second_referee_count,
    COUNT(CASE WHEN mr.role = 'CHALLENGE' THEN 1 END)::bigint as challenge_referee_count
  FROM match_referees mr
  WHERE mr.referee_id = referee_id_param;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function for match results aggregation
CREATE OR REPLACE FUNCTION get_match_results_aggregation(event_id_param bigint)
RETURNS TABLE (
  total_matches bigint,
  matches_with_results bigint,
  straight_set_wins bigint,
  three_set_matches bigint,
  average_match_duration interval
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*)::bigint as total_matches,
    COUNT(CASE WHEN m.result IS NOT NULL THEN 1 END)::bigint as matches_with_results,
    COUNT(CASE WHEN jsonb_array_length(m.sets) = 2 THEN 1 END)::bigint as straight_set_wins,
    COUNT(CASE WHEN jsonb_array_length(m.sets) = 3 THEN 1 END)::bigint as three_set_matches,
    AVG(
      CASE 
        WHEN m.local_datetime IS NOT NULL AND m.utc_datetime IS NOT NULL 
        THEN m.local_datetime - m.utc_datetime 
        ELSE NULL 
      END
    ) as average_match_duration
  FROM matches m
  WHERE m.event_id = event_id_param;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function for performance-optimized common queries
CREATE OR REPLACE FUNCTION get_matches_by_tournament_and_date(
  tournament_code_param text,
  start_date_param date,
  end_date_param date
)
RETURNS TABLE (
  match_id bigint,
  vis_match_no bigint,
  event_id bigint,
  round_name text,
  utc_datetime timestamptz,
  court text,
  team_a_name text,
  team_b_name text,
  status text,
  referee_count bigint
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    m.id as match_id,
    m.vis_match_no,
    m.event_id,
    m.round_name,
    m.utc_datetime,
    m.court,
    m.team_a_name,
    m.team_b_name,
    m.status,
    COUNT(mr.referee_id)::bigint as referee_count
  FROM matches m
  LEFT JOIN match_referees mr ON m.id = mr.match_id
  WHERE m.tournament_code = tournament_code_param
    AND DATE(m.utc_datetime) BETWEEN start_date_param AND end_date_param
  GROUP BY m.id, m.vis_match_no, m.event_id, m.round_name, m.utc_datetime, 
           m.court, m.team_a_name, m.team_b_name, m.status
  ORDER BY m.utc_datetime;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permissions to service role
GRANT EXECUTE ON FUNCTION get_match_statistics_by_tournament(text) TO service_role;
GRANT EXECUTE ON FUNCTION get_referee_assignment_counts(bigint) TO service_role;
GRANT EXECUTE ON FUNCTION get_match_results_aggregation(bigint) TO service_role;
GRANT EXECUTE ON FUNCTION get_matches_by_tournament_and_date(text, date, date) TO service_role;
GRANT EXECUTE ON FUNCTION update_events_timestamp() TO service_role;
GRANT EXECUTE ON FUNCTION update_matches_timestamp() TO service_role;

-- =============================================================================
-- REAL-TIME CONFIGURATION
-- =============================================================================

-- Enable real-time subscriptions for events, matches, and match_referees
DO $$
BEGIN
  -- Add events to real-time publication
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE events;
  END IF;
EXCEPTION
  WHEN duplicate_object THEN
    -- Table already added to real-time publication, ignore error
    NULL;
END $$;

DO $$
BEGIN
  -- Add matches to real-time publication
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE matches;
  END IF;
EXCEPTION
  WHEN duplicate_object THEN
    -- Table already added to real-time publication, ignore error
    NULL;
END $$;

DO $$
BEGIN
  -- Add match_referees to real-time publication
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE match_referees;
  END IF;
EXCEPTION
  WHEN duplicate_object THEN
    -- Table already added to real-time publication, ignore error
    NULL;
END $$;

-- =============================================================================
-- DATA VALIDATION FUNCTIONS
-- =============================================================================

-- Function to validate match schema data integrity
CREATE OR REPLACE FUNCTION validate_match_schema_data()
RETURNS TABLE (
  validation_result text,
  record_count bigint,
  issue_description text
) AS $$
BEGIN
  -- Check for duplicate vis_event_no
  RETURN QUERY
  SELECT 
    'duplicate_vis_event_no'::text,
    COUNT(*)::bigint,
    'Duplicate VIS event numbers found'::text
  FROM events 
  GROUP BY vis_event_no 
  HAVING COUNT(*) > 1;
  
  -- Check for duplicate vis_match_no
  RETURN QUERY
  SELECT 
    'duplicate_vis_match_no'::text,
    COUNT(*)::bigint,
    'Duplicate VIS match numbers found'::text
  FROM matches 
  GROUP BY vis_match_no 
  HAVING COUNT(*) > 1;
  
  -- Check for invalid gender values in events
  RETURN QUERY
  SELECT 
    'invalid_gender_events'::text,
    COUNT(*)::bigint,
    'Invalid gender values found in events (not M or W)'::text
  FROM events 
  WHERE gender IS NOT NULL AND gender NOT IN ('M', 'W');
  
  -- Check for missing required fields in events
  RETURN QUERY
  SELECT 
    'missing_required_fields_events'::text,
    COUNT(*)::bigint,
    'Events with missing vis_event_no or tournament_id'::text
  FROM events 
  WHERE vis_event_no IS NULL OR tournament_id IS NULL;
  
  -- Check for missing required fields in matches
  RETURN QUERY
  SELECT 
    'missing_required_fields_matches'::text,
    COUNT(*)::bigint,
    'Matches with missing vis_match_no, tournament_code, or event_id'::text
  FROM matches 
  WHERE vis_match_no IS NULL OR tournament_code IS NULL OR event_id IS NULL;
  
  -- Check for invalid referee roles
  RETURN QUERY
  SELECT 
    'invalid_referee_roles'::text,
    COUNT(*)::bigint,
    'Invalid referee roles found (not FIRST, SECOND, or CHALLENGE)'::text
  FROM match_referees 
  WHERE role NOT IN ('FIRST', 'SECOND', 'CHALLENGE');
  
  -- Check for orphaned matches (event_id not in events)
  RETURN QUERY
  SELECT 
    'orphaned_matches'::text,
    COUNT(*)::bigint,
    'Matches with event_id not found in events table'::text
  FROM matches m
  WHERE NOT EXISTS (SELECT 1 FROM events e WHERE e.id = m.event_id);
  
  -- Check for orphaned match_referees (match_id not in matches)
  RETURN QUERY
  SELECT 
    'orphaned_match_referees'::text,
    COUNT(*)::bigint,
    'Match referees with match_id not found in matches table'::text
  FROM match_referees mr
  WHERE NOT EXISTS (SELECT 1 FROM matches m WHERE m.id = mr.match_id);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permissions to service role
GRANT EXECUTE ON FUNCTION validate_match_schema_data() TO service_role;

-- =============================================================================
-- SCHEMA VERSION UPDATE
-- =============================================================================

-- Update schema version record
INSERT INTO schema_versions (version, description) VALUES
('2.2.0', 'Match schema with events, matches, and match_referees tables including aggregation functions')
ON CONFLICT (version) DO NOTHING;

-- =============================================================================
-- VALIDATION QUERIES
-- =============================================================================

-- Verify new tables were created successfully
DO $$
BEGIN
  -- Check events table exists
  ASSERT (SELECT COUNT(*) FROM information_schema.tables 
          WHERE table_name = 'events') = 1,
          'Events table was not created';
          
  -- Check matches table exists
  ASSERT (SELECT COUNT(*) FROM information_schema.tables 
          WHERE table_name = 'matches') = 1,
          'Matches table was not created';
          
  -- Check match_referees table exists
  ASSERT (SELECT COUNT(*) FROM information_schema.tables 
          WHERE table_name = 'match_referees') = 1,
          'Match_referees table was not created';
          
  -- Check required columns exist in events
  ASSERT (SELECT COUNT(*) FROM information_schema.columns 
          WHERE table_name = 'events' 
          AND column_name IN ('vis_event_no', 'tournament_id', 'gender', 'phase')) = 4,
          'Required columns missing from events table';
          
  -- Check required columns exist in matches
  ASSERT (SELECT COUNT(*) FROM information_schema.columns 
          WHERE table_name = 'matches' 
          AND column_name IN ('vis_match_no', 'tournament_code', 'event_id', 'sets', 'result')) = 5,
          'Required columns missing from matches table';
          
  -- Check unique constraints exist
  ASSERT (SELECT COUNT(*) FROM information_schema.table_constraints 
          WHERE table_name IN ('events', 'matches') 
          AND constraint_type = 'UNIQUE') >= 2,
          'Unique constraints missing from events or matches tables';
          
  -- Check indexes were created
  ASSERT (SELECT COUNT(*) FROM pg_indexes 
          WHERE tablename IN ('events', 'matches', 'match_referees')) >= 8,
          'Required indexes missing from match schema tables';
          
  -- Check RLS is enabled on all tables
  ASSERT (SELECT COUNT(*) FROM pg_class 
          WHERE relname IN ('events', 'matches', 'match_referees') 
          AND relrowsecurity = true) = 3,
          'Row Level Security not enabled on all match schema tables';
          
  -- Check foreign key relationships exist
  ASSERT (SELECT COUNT(*) FROM information_schema.table_constraints 
          WHERE constraint_type = 'FOREIGN KEY' 
          AND table_name IN ('events', 'matches', 'match_referees')) >= 4,
          'Foreign key constraints missing from match schema tables';
          
  RAISE NOTICE 'Match schema migration completed successfully';
END $$;