/**
 * Unit Tests for RefereeAnalyticsExportService
 * Story 4.2: Referee Performance Analytics - Task 6
 */

import RefereeAnalyticsExportService, { REPORT_TEMPLATES } from '../RefereeAnalyticsExportService';
import { RefereePerformanceMetrics } from '../../hooks/useRefereeAnalytics';

// Mock ErrorLogger
jest.mock('../ErrorLogger', () => ({
  ErrorLogger: {
    getInstance: () => ({
      logError: jest.fn(),
    }),
  },
}));

// Mock performance API
Object.defineProperty(global, 'performance', {
  value: {
    now: jest.fn(() => 123.456),
  },
});

// Test data
const mockRefereeData: RefereePerformanceMetrics[] = [
  {
    referee_id: '1',
    referee_name: 'John Smith',
    federation_code: 'FIVB',
    total_assignments: 15,
    first_referee_count: 8,
    second_referee_count: 5,
    challenge_referee_count: 2,
    completion_rate: 95,
    tournaments_worked: ['TOUR001', 'TOUR002'],
    performance_score: 88,
    workload_trend: 'stable',
    geographic_coverage: ['Location1', 'Location2'],
    avg_matches_per_day: 3.2,
  },
  {
    referee_id: '2',
    referee_name: 'Jane Doe',
    federation_code: 'CEV',
    total_assignments: 22,
    first_referee_count: 12,
    second_referee_count: 8,
    challenge_referee_count: 2,
    completion_rate: 98,
    tournaments_worked: ['TOUR001', 'TOUR003', 'TOUR004'],
    performance_score: 94,
    workload_trend: 'increasing',
    geographic_coverage: ['Location1', 'Location3', 'Location4'],
    avg_matches_per_day: 4.5,
  },
  {
    referee_id: '3',
    referee_name: 'Bob Johnson',
    federation_code: 'FIVB',
    total_assignments: 8,
    first_referee_count: 3,
    second_referee_count: 4,
    challenge_referee_count: 1,
    completion_rate: 100,
    tournaments_worked: ['TOUR002'],
    performance_score: 76,
    workload_trend: 'decreasing',
    geographic_coverage: ['Location2'],
    avg_matches_per_day: 2.1,
  },
];

describe('RefereeAnalyticsExportService', () => {
  let exportService: RefereeAnalyticsExportService;

  beforeEach(() => {
    exportService = RefereeAnalyticsExportService.getInstance();
  });

  describe('singleton pattern', () => {
    it('should return the same instance', () => {
      const instance1 = RefereeAnalyticsExportService.getInstance();
      const instance2 = RefereeAnalyticsExportService.getInstance();
      expect(instance1).toBe(instance2);
    });
  });

  describe('CSV export', () => {
    it('should export data to CSV format', async () => {
      const blob = await exportService.exportAnalytics(mockRefereeData, 'csv');
      
      expect(blob).toBeInstanceOf(Blob);
      expect(blob.type).toBe('text/csv;charset=utf-8;');

      const text = await blob.text();
      expect(text).toContain('Referee Name,Federation Code');
      expect(text).toContain('John Smith,FIVB');
      expect(text).toContain('Jane Doe,CEV');
    });

    it('should include metadata in CSV when provided', async () => {
      const config = {
        metadata: {
          title: 'Test Report',
          description: 'Test Description',
          generatedBy: 'Test User',
          generatedAt: '2025-01-09T12:00:00Z',
        },
      };

      const blob = await exportService.exportAnalytics(mockRefereeData, 'csv', config);
      const text = await blob.text();
      
      expect(text).toContain('# Test Report');
      expect(text).toContain('# Test Description');
      expect(text).toContain('# Generated by: Test User');
      expect(text).toContain('# Total records: 3');
    });

    it('should include summary statistics when template specifies', async () => {
      const config = {
        template: REPORT_TEMPLATES.performance_summary,
      };

      const blob = await exportService.exportAnalytics(mockRefereeData, 'csv', config);
      const text = await blob.text();
      
      expect(text).toContain('# SUMMARY STATISTICS');
      expect(text).toContain('Total Referees,3');
      expect(text).toContain('Total Assignments,45'); // 15 + 22 + 8
      expect(text).toContain('Average Performance Score,86%'); // (88 + 94 + 76) / 3
    });

    it('should handle array values in CSV', async () => {
      const blob = await exportService.exportAnalytics(mockRefereeData, 'csv');
      const text = await blob.text();
      
      // Tournament arrays should be joined with semicolons
      expect(text).toContain('TOUR001;TOUR002');
      expect(text).toContain('TOUR001;TOUR003;TOUR004');
    });

    it('should escape commas and quotes in CSV', async () => {
      const dataWithCommas: RefereePerformanceMetrics[] = [{
        ...mockRefereeData[0],
        referee_name: 'John "The Great" Smith, Jr.',
      }];

      const blob = await exportService.exportAnalytics(dataWithCommas, 'csv');
      const text = await blob.text();
      
      expect(text).toContain('"John ""The Great"" Smith, Jr."');
    });
  });

  describe('JSON export', () => {
    it('should export data to JSON format', async () => {
      const blob = await exportService.exportAnalytics(mockRefereeData, 'json');
      
      expect(blob).toBeInstanceOf(Blob);
      expect(blob.type).toBe('application/json;charset=utf-8;');

      const text = await blob.text();
      const data = JSON.parse(text);
      
      expect(data).toHaveProperty('metadata');
      expect(data).toHaveProperty('data');
      expect(data.data).toHaveLength(3);
      expect(data.metadata.totalRecords).toBe(3);
    });

    it('should include only specified columns when template is provided', async () => {
      const config = {
        template: {
          name: 'Test Template',
          description: 'Test',
          includeColumns: ['referee_name', 'performance_score'],
          sortBy: 'performance_score' as keyof RefereePerformanceMetrics,
        },
      };

      const blob = await exportService.exportAnalytics(mockRefereeData, 'json', config);
      const text = await blob.text();
      const data = JSON.parse(text);
      
      expect(data.data[0]).toHaveProperty('referee_name');
      expect(data.data[0]).toHaveProperty('performance_score');
      expect(data.data[0]).not.toHaveProperty('federation_code');
    });

    it('should sort data according to template', async () => {
      const config = {
        template: {
          name: 'Test Template',
          description: 'Test',
          includeColumns: ['referee_name', 'performance_score'],
          sortBy: 'performance_score' as keyof RefereePerformanceMetrics,
        },
      };

      const blob = await exportService.exportAnalytics(mockRefereeData, 'json', config);
      const text = await blob.text();
      const data = JSON.parse(text);
      
      // Should be sorted by performance_score descending (94, 88, 76)
      expect(data.data[0].performance_score).toBe(94);
      expect(data.data[1].performance_score).toBe(88);
      expect(data.data[2].performance_score).toBe(76);
    });

    it('should group data when specified', async () => {
      const config = {
        template: {
          name: 'Test Template',
          description: 'Test',
          includeColumns: ['referee_name', 'federation_code'],
          sortBy: 'performance_score' as keyof RefereePerformanceMetrics,
          groupBy: 'federation' as any,
        },
      };

      const blob = await exportService.exportAnalytics(mockRefereeData, 'json', config);
      const text = await blob.text();
      const data = JSON.parse(text);
      
      expect(data.data).toHaveProperty('FIVB');
      expect(data.data).toHaveProperty('CEV');
      expect(data.data.FIVB).toHaveLength(2); // John Smith and Bob Johnson
      expect(data.data.CEV).toHaveLength(1); // Jane Doe
    });
  });

  describe('PDF export', () => {
    it('should export data to PDF format (HTML)', async () => {
      const blob = await exportService.exportAnalytics(mockRefereeData, 'pdf');
      
      expect(blob).toBeInstanceOf(Blob);
      expect(blob.type).toBe('text/html;charset=utf-8;');

      const text = await blob.text();
      expect(text).toContain('<!DOCTYPE html>');
      expect(text).toContain('<table>');
      expect(text).toContain('John Smith');
      expect(text).toContain('Jane Doe');
    });

    it('should include summary section in PDF when specified', async () => {
      const config = {
        template: REPORT_TEMPLATES.performance_summary,
      };

      const blob = await exportService.exportAnalytics(mockRefereeData, 'pdf', config);
      const text = await blob.text();
      
      expect(text).toContain('Summary Statistics');
      expect(text).toContain('Total Referees:</strong> 3');
      expect(text).toContain('Total Assignments:</strong> 45');
    });
  });

  describe('data filtering', () => {
    it('should filter by performance score', async () => {
      const config = {
        filters: {
          minPerformanceScore: 85,
        },
      };

      const blob = await exportService.exportAnalytics(mockRefereeData, 'json', config);
      const text = await blob.text();
      const data = JSON.parse(text);
      
      expect(data.data).toHaveLength(2); // Only John (88) and Jane (94)
      expect(data.data.every((r: any) => r.performance_score >= 85)).toBe(true);
    });

    it('should filter by federation codes', async () => {
      const config = {
        filters: {
          federationCodes: ['FIVB'],
        },
      };

      const blob = await exportService.exportAnalytics(mockRefereeData, 'json', config);
      const text = await blob.text();
      const data = JSON.parse(text);
      
      expect(data.data).toHaveLength(2); // Only John and Bob
      expect(data.data.every((r: any) => r.federation_code === 'FIVB')).toBe(true);
    });

    it('should exclude inactive referees when specified', async () => {
      const dataWithInactive = [
        ...mockRefereeData,
        {
          ...mockRefereeData[0],
          referee_id: '4',
          referee_name: 'Inactive Referee',
          total_assignments: 0,
        },
      ];

      const config = {
        filters: {
          includeInactive: false,
        },
      };

      const blob = await exportService.exportAnalytics(dataWithInactive, 'json', config);
      const text = await blob.text();
      const data = JSON.parse(text);
      
      expect(data.data).toHaveLength(3); // Excludes inactive referee
      expect(data.data.every((r: any) => r.total_assignments > 0)).toBe(true);
    });
  });

  describe('report templates', () => {
    it('should have predefined templates available', () => {
      const templates = exportService.getAvailableTemplates();
      
      expect(templates).toHaveProperty('performance_summary');
      expect(templates).toHaveProperty('workload_analysis');
      expect(templates).toHaveProperty('federation_comparison');
      expect(templates).toHaveProperty('top_performers');
      expect(templates).toHaveProperty('assignment_overview');
      
      expect(templates.performance_summary.name).toBe('Performance Summary');
      expect(templates.workload_analysis.sortBy).toBe('avg_matches_per_day');
    });

    it('should create custom templates', () => {
      const customTemplate = exportService.createCustomTemplate('Custom Test', {
        description: 'Custom test template',
        includeColumns: ['referee_name', 'total_assignments'],
        sortBy: 'total_assignments',
      });
      
      expect(customTemplate.name).toBe('Custom Test');
      expect(customTemplate.description).toBe('Custom test template');
      expect(customTemplate.includeColumns).toEqual(['referee_name', 'total_assignments']);
      expect(customTemplate.sortBy).toBe('total_assignments');
    });
  });

  describe('error handling', () => {
    it('should handle unsupported export format', async () => {
      await expect(
        exportService.exportAnalytics(mockRefereeData, 'xml' as any)
      ).rejects.toThrow('Unsupported export format: xml');
    });

    it('should handle empty data gracefully', async () => {
      const blob = await exportService.exportAnalytics([], 'csv');
      const text = await blob.text();
      
      expect(text).toContain('Referee Name,Federation Code'); // Headers still present
      expect(text).toContain('Total Referees,0'); // Summary shows 0
    });

    it('should handle null values gracefully', async () => {
      const dataWithNulls = [{
        ...mockRefereeData[0],
        federation_code: null as any,
        tournaments_worked: null as any,
      }];

      const blob = await exportService.exportAnalytics(dataWithNulls, 'csv');
      const text = await blob.text();
      
      expect(text).toContain('John Smith,'); // Null federation becomes empty
      expect(text).not.toContain('null');
    });
  });

  describe('summary statistics', () => {
    it('should calculate correct summary statistics', async () => {
      const blob = await exportService.exportAnalytics(mockRefereeData, 'json', {
        template: { ...REPORT_TEMPLATES.performance_summary, includeSummary: true },
      });
      const text = await blob.text();
      const data = JSON.parse(text);
      
      expect(data.summary.totalReferees).toBe(3);
      expect(data.summary.totalAssignments).toBe(45); // 15 + 22 + 8
      expect(data.summary.avgPerformanceScore).toBe(86); // (88 + 94 + 76) / 3
      expect(data.summary.avgWorkload).toBe(3.27); // (3.2 + 4.5 + 2.1) / 3, rounded
      expect(data.summary.activeReferees).toBe(3); // All have assignments > 0
    });
  });

  describe('performance logging', () => {
    it('should log performance metrics on successful export', async () => {
      const consoleSpy = jest.spyOn(console, 'log').mockImplementation();
      
      await exportService.exportAnalytics(mockRefereeData, 'csv');
      
      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringMatching(/Export completed: CSV \| 3 records \| \d+ms/)
      );
      
      consoleSpy.mockRestore();
    });
  });
});