-- Migration 007: Create New Tournament Schema
-- This migration implements the new tournament schema as specified in Story 2.1
-- Replaces the existing tournaments table with analytics-ready structure

-- =============================================================================
-- BACKUP AND DROP EXISTING TABLE
-- =============================================================================

-- Create backup of existing tournaments data
CREATE TABLE IF NOT EXISTS tournaments_backup AS 
SELECT * FROM tournaments;

-- Drop existing tournament table and its dependencies
DROP TABLE IF EXISTS tournaments CASCADE;

-- =============================================================================
-- NEW TOURNAMENT TABLE SCHEMA
-- =============================================================================

-- Create new tournaments table with proper normalization and analytics-ready structure
CREATE TABLE IF NOT EXISTS tournaments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vis_tournament_no bigint NOT NULL UNIQUE,   -- VIS: No
  tournament_code text NOT NULL UNIQUE,       -- VIS: Code
  name text NOT NULL,                         -- VIS: Title/Name
  country text,                               -- VIS: CountryCode
  city text,
  season int,                                 -- VIS: Season
  gender text CHECK (gender IN ('M','W')),
  type text,                                  -- Elite, Challenge, Futures...
  start_qualification date,
  start_main_draw date,
  status text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- =============================================================================
-- ANALYTICS-READY INDEXES
-- =============================================================================

-- Composite index for tournament filtering by season and gender
CREATE INDEX idx_tournaments_season_gender ON tournaments (season, gender);

-- Index for date-based queries
CREATE INDEX idx_tournaments_start_main_draw ON tournaments (start_main_draw);

-- Index for status filtering
CREATE INDEX idx_tournaments_status_new ON tournaments (status);

-- Index for geographic filtering
CREATE INDEX idx_tournaments_country ON tournaments (country);

-- Index for VIS tournament number lookups
CREATE INDEX idx_tournaments_vis_tournament_no ON tournaments (vis_tournament_no);

-- Index for tournament code lookups
CREATE INDEX idx_tournaments_tournament_code ON tournaments (tournament_code);

-- =============================================================================
-- ROW LEVEL SECURITY POLICIES
-- =============================================================================

-- Enable Row Level Security on tournaments table
ALTER TABLE tournaments ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "anon_read" ON tournaments;
DROP POLICY IF EXISTS "service_upsert" ON tournaments;
DROP POLICY IF EXISTS "service_update" ON tournaments;

-- Create anon_read policy allowing public SELECT access
CREATE POLICY "anon_read" ON tournaments
FOR SELECT USING (true);

-- Create service_upsert policy for INSERT operations (service_role only)
CREATE POLICY "service_upsert" ON tournaments
FOR INSERT WITH CHECK (auth.role() = 'service_role');

-- Create service_update policy for UPDATE operations (service_role only)  
CREATE POLICY "service_update" ON tournaments
FOR UPDATE USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

-- Create service_delete policy for DELETE operations (service_role only)
CREATE POLICY "service_delete" ON tournaments
FOR DELETE USING (auth.role() = 'service_role');

-- =============================================================================
-- AUTOMATIC TIMESTAMP TRIGGERS
-- =============================================================================

-- Create or replace function to update timestamp on record changes
CREATE OR REPLACE FUNCTION update_tournaments_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for automatic timestamp updates
DROP TRIGGER IF EXISTS update_tournaments_timestamp_trigger ON tournaments;
CREATE TRIGGER update_tournaments_timestamp_trigger
  BEFORE UPDATE ON tournaments
  FOR EACH ROW
  EXECUTE FUNCTION update_tournaments_timestamp();

-- =============================================================================
-- REAL-TIME CONFIGURATION
-- =============================================================================

-- Enable real-time subscriptions for tournaments
DO $$
BEGIN
  -- Add tournaments to real-time publication
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE tournaments;
  END IF;
EXCEPTION
  WHEN duplicate_object THEN
    -- Table already added to real-time publication, ignore error
    NULL;
END $$;

-- =============================================================================
-- UPDATE MATCHES TABLE FOREIGN KEY (DEFENSIVE)
-- =============================================================================

-- Update matches table to reference new tournament structure
-- This section is defensive and handles cases where matches table may not exist
DO $$
BEGIN
  -- Check if matches table exists before attempting to modify it
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'matches') THEN
    -- Drop existing foreign key constraint if it exists
    EXECUTE 'ALTER TABLE matches DROP CONSTRAINT IF EXISTS matches_tournament_no_fkey';
    
    -- Check if tournament_no column exists in matches table
    IF EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_name = 'matches' AND column_name = 'tournament_no'
    ) THEN
      -- Add new foreign key constraint referencing vis_tournament_no
      -- Note: This assumes matches.tournament_no contains VIS tournament numbers
      EXECUTE 'ALTER TABLE matches 
               ADD CONSTRAINT matches_tournament_vis_no_fkey 
               FOREIGN KEY (tournament_no) REFERENCES tournaments(vis_tournament_no) ON DELETE CASCADE';
      
      RAISE NOTICE 'Updated matches table foreign key constraint to reference tournaments.vis_tournament_no';
    ELSE
      RAISE WARNING 'matches table exists but tournament_no column not found - skipping foreign key constraint';
    END IF;
  ELSE
    RAISE NOTICE 'matches table does not exist yet - foreign key constraint will be added when matches table is created';
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE WARNING 'Failed to update matches table foreign key: %', SQLERRM;
END $$;

-- =============================================================================
-- DATA VALIDATION FUNCTIONS
-- =============================================================================

-- Function to validate tournament data integrity
CREATE OR REPLACE FUNCTION validate_tournament_data()
RETURNS TABLE (
  validation_result text,
  record_count bigint,
  issue_description text
) AS $$
BEGIN
  -- Check for duplicate vis_tournament_no
  RETURN QUERY
  SELECT 
    'duplicate_vis_tournament_no'::text,
    COUNT(*)::bigint,
    'Duplicate VIS tournament numbers found'::text
  FROM tournaments 
  GROUP BY vis_tournament_no 
  HAVING COUNT(*) > 1;
  
  -- Check for duplicate tournament_code
  RETURN QUERY
  SELECT 
    'duplicate_tournament_code'::text,
    COUNT(*)::bigint,
    'Duplicate tournament codes found'::text
  FROM tournaments 
  GROUP BY tournament_code 
  HAVING COUNT(*) > 1;
  
  -- Check for invalid gender values
  RETURN QUERY
  SELECT 
    'invalid_gender'::text,
    COUNT(*)::bigint,
    'Invalid gender values found (not M or W)'::text
  FROM tournaments 
  WHERE gender IS NOT NULL AND gender NOT IN ('M', 'W');
  
  -- Check for missing required fields
  RETURN QUERY
  SELECT 
    'missing_required_fields'::text,
    COUNT(*)::bigint,
    'Records with missing vis_tournament_no, tournament_code, or name'::text
  FROM tournaments 
  WHERE vis_tournament_no IS NULL 
     OR tournament_code IS NULL 
     OR name IS NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permissions to service role
GRANT EXECUTE ON FUNCTION validate_tournament_data() TO service_role;
GRANT EXECUTE ON FUNCTION update_tournaments_timestamp() TO service_role;

-- =============================================================================
-- SCHEMA VERSION UPDATE
-- =============================================================================

-- Update schema version record
INSERT INTO schema_versions (version, description) VALUES
('2.1.0', 'New tournament schema with VIS compatibility and analytics-ready structure')
ON CONFLICT (version) DO NOTHING;

-- =============================================================================
-- VALIDATION QUERIES
-- =============================================================================

-- Verify new tournament table was created successfully
DO $$
BEGIN
  -- Check table exists
  ASSERT (SELECT COUNT(*) FROM information_schema.tables 
          WHERE table_name = 'tournaments') = 1,
          'New tournaments table was not created';
          
  -- Check required columns exist
  ASSERT (SELECT COUNT(*) FROM information_schema.columns 
          WHERE table_name = 'tournaments' 
          AND column_name IN ('vis_tournament_no', 'tournament_code', 'name', 'gender', 'season')) = 5,
          'Required columns missing from tournaments table';
          
  -- Check unique constraints exist
  ASSERT (SELECT COUNT(*) FROM information_schema.table_constraints 
          WHERE table_name = 'tournaments' 
          AND constraint_type = 'UNIQUE') >= 2,
          'Unique constraints missing from tournaments table';
          
  -- Check indexes were created
  ASSERT (SELECT COUNT(*) FROM pg_indexes 
          WHERE tablename = 'tournaments') >= 6,
          'Required indexes missing from tournaments table';
          
  -- Check RLS is enabled
  ASSERT (SELECT relrowsecurity FROM pg_class WHERE relname = 'tournaments') = true,
          'Row Level Security not enabled on tournaments table';
          
  RAISE NOTICE 'New tournament schema migration completed successfully';
END $$;