-- Migration 010: Create Sync Status Schema
-- This migration implements the sync monitoring schema as specified in Story 5.1
-- Creates sync_status table for tracking VIS-to-Database synchronization operations

-- =============================================================================
-- BACKUP AND DROP EXISTING SYNC_STATUS TABLE
-- =============================================================================

-- Create backup of existing sync_status data
CREATE TABLE IF NOT EXISTS sync_status_legacy_backup AS 
SELECT * FROM sync_status;

-- Drop existing sync_status table and recreate with new schema
DROP TABLE IF EXISTS sync_status CASCADE;

-- =============================================================================
-- SYNC STATUS TABLE SCHEMA
-- =============================================================================

-- Create sync_status table for monitoring synchronization operations
CREATE TABLE IF NOT EXISTS sync_status (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_id text NOT NULL UNIQUE,
  status text CHECK (status IN ('pending','running','completed','failed')) NOT NULL,
  start_time timestamptz NOT NULL,
  end_time timestamptz,
  records_processed bigint DEFAULT 0,
  errors text[] DEFAULT '{}',
  last_error text,
  sync_type text DEFAULT 'full', -- 'full', 'incremental', 'tournaments', 'matches', 'referees'
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- =============================================================================
-- SYNC STATUS INDEXES
-- =============================================================================

-- Index for sync_id lookups (unique constraint already creates index)
-- CREATE INDEX idx_sync_status_sync_id ON sync_status (sync_id); -- Redundant due to UNIQUE constraint

-- Index for status filtering
CREATE INDEX idx_sync_status_status ON sync_status (status);

-- Index for time-based queries
CREATE INDEX idx_sync_status_start_time ON sync_status (start_time DESC);
CREATE INDEX idx_sync_status_end_time ON sync_status (end_time DESC);

-- Index for sync type filtering
CREATE INDEX idx_sync_status_type ON sync_status (sync_type);

-- Composite index for monitoring queries
CREATE INDEX idx_sync_status_status_start_time ON sync_status (status, start_time DESC);

-- =============================================================================
-- ROW LEVEL SECURITY POLICIES
-- =============================================================================

-- Enable Row Level Security on sync_status table
ALTER TABLE sync_status ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "anon_read" ON sync_status;
DROP POLICY IF EXISTS "service_upsert" ON sync_status;
DROP POLICY IF EXISTS "service_update" ON sync_status;
DROP POLICY IF EXISTS "service_delete" ON sync_status;

-- Create anon_read policy allowing public SELECT access for monitoring dashboards
CREATE POLICY "anon_read" ON sync_status
FOR SELECT USING (true);

-- Create service_upsert policy for INSERT operations (service_role only)
CREATE POLICY "service_upsert" ON sync_status
FOR INSERT WITH CHECK (auth.role() = 'service_role');

-- Create service_update policy for UPDATE operations (service_role only)  
CREATE POLICY "service_update" ON sync_status
FOR UPDATE USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

-- Create service_delete policy for DELETE operations (service_role only)
CREATE POLICY "service_delete" ON sync_status
FOR DELETE USING (auth.role() = 'service_role');

-- =============================================================================
-- AUTOMATIC TIMESTAMP TRIGGERS
-- =============================================================================

-- Create or replace function to update timestamp on record changes
CREATE OR REPLACE FUNCTION update_sync_status_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for automatic timestamp updates
DROP TRIGGER IF EXISTS update_sync_status_timestamp_trigger ON sync_status;
CREATE TRIGGER update_sync_status_timestamp_trigger
  BEFORE UPDATE ON sync_status
  FOR EACH ROW
  EXECUTE FUNCTION update_sync_status_timestamp();

-- =============================================================================
-- REAL-TIME CONFIGURATION
-- =============================================================================

-- Enable real-time subscriptions for sync_status
DO $$
BEGIN
  -- Add sync_status to real-time publication
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE sync_status;
  END IF;
EXCEPTION
  WHEN duplicate_object THEN
    -- Table already added to real-time publication, ignore error
    NULL;
END $$;

-- =============================================================================
-- SYNC MONITORING FUNCTIONS
-- =============================================================================

-- Function to get sync status summary
CREATE OR REPLACE FUNCTION get_sync_status_summary()
RETURNS TABLE (
  total_syncs bigint,
  running_syncs bigint,
  completed_syncs bigint,
  failed_syncs bigint,
  last_successful_sync timestamptz,
  last_failed_sync timestamptz,
  average_sync_duration interval
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*)::bigint as total_syncs,
    COUNT(CASE WHEN ss.status = 'running' THEN 1 END)::bigint as running_syncs,
    COUNT(CASE WHEN ss.status = 'completed' THEN 1 END)::bigint as completed_syncs,
    COUNT(CASE WHEN ss.status = 'failed' THEN 1 END)::bigint as failed_syncs,
    MAX(CASE WHEN ss.status = 'completed' THEN ss.end_time END) as last_successful_sync,
    MAX(CASE WHEN ss.status = 'failed' THEN ss.end_time END) as last_failed_sync,
    AVG(
      CASE 
        WHEN ss.status IN ('completed', 'failed') AND ss.end_time IS NOT NULL 
        THEN ss.end_time - ss.start_time 
        ELSE NULL 
      END
    ) as average_sync_duration
  FROM sync_status ss;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get recent sync performance metrics
CREATE OR REPLACE FUNCTION get_sync_performance_metrics(days_back integer DEFAULT 7)
RETURNS TABLE (
  sync_date date,
  total_syncs bigint,
  successful_syncs bigint,
  failed_syncs bigint,
  total_records_processed bigint,
  success_rate numeric,
  average_duration interval
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    DATE(ss.start_time) as sync_date,
    COUNT(*)::bigint as total_syncs,
    COUNT(CASE WHEN ss.status = 'completed' THEN 1 END)::bigint as successful_syncs,
    COUNT(CASE WHEN ss.status = 'failed' THEN 1 END)::bigint as failed_syncs,
    SUM(ss.records_processed)::bigint as total_records_processed,
    CASE 
      WHEN COUNT(*) > 0 THEN 
        ROUND(COUNT(CASE WHEN ss.status = 'completed' THEN 1 END) * 100.0 / COUNT(*), 2)
      ELSE 0
    END as success_rate,
    AVG(
      CASE 
        WHEN ss.status IN ('completed', 'failed') AND ss.end_time IS NOT NULL 
        THEN ss.end_time - ss.start_time 
        ELSE NULL 
      END
    ) as average_duration
  FROM sync_status ss
  WHERE ss.start_time >= CURRENT_DATE - INTERVAL '%s days' % days_back
  GROUP BY DATE(ss.start_time)
  ORDER BY sync_date DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to cleanup old sync status records
CREATE OR REPLACE FUNCTION cleanup_old_sync_status(days_to_keep integer DEFAULT 30)
RETURNS TABLE (
  deleted_count bigint,
  cleanup_timestamp timestamptz
) AS $$
DECLARE
  deleted_rows bigint;
BEGIN
  -- Delete sync status records older than specified days
  DELETE FROM sync_status 
  WHERE start_time < CURRENT_TIMESTAMP - INTERVAL '%s days' % days_to_keep;
  
  GET DIAGNOSTICS deleted_rows = ROW_COUNT;
  
  RETURN QUERY
  SELECT 
    deleted_rows as deleted_count,
    NOW() as cleanup_timestamp;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get running sync details (for monitoring)
CREATE OR REPLACE FUNCTION get_running_sync_details()
RETURNS TABLE (
  sync_id text,
  start_time timestamptz,
  duration interval,
  records_processed bigint,
  sync_type text
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    ss.sync_id,
    ss.start_time,
    NOW() - ss.start_time as duration,
    ss.records_processed,
    ss.sync_type
  FROM sync_status ss
  WHERE ss.status = 'running'
  ORDER BY ss.start_time;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permissions to service role
GRANT EXECUTE ON FUNCTION get_sync_status_summary() TO service_role;
GRANT EXECUTE ON FUNCTION get_sync_performance_metrics(integer) TO service_role;
GRANT EXECUTE ON FUNCTION cleanup_old_sync_status(integer) TO service_role;
GRANT EXECUTE ON FUNCTION get_running_sync_details() TO service_role;
GRANT EXECUTE ON FUNCTION update_sync_status_timestamp() TO service_role;

-- =============================================================================
-- DATA VALIDATION FUNCTIONS
-- =============================================================================

-- Function to validate sync status data integrity
CREATE OR REPLACE FUNCTION validate_sync_status_data()
RETURNS TABLE (
  validation_result text,
  record_count bigint,
  issue_description text
) AS $$
BEGIN
  -- Check for duplicate sync_id
  RETURN QUERY
  SELECT 
    'duplicate_sync_id'::text,
    COUNT(*)::bigint,
    'Duplicate sync IDs found'::text
  FROM sync_status 
  GROUP BY sync_id 
  HAVING COUNT(*) > 1;
  
  -- Check for invalid status values
  RETURN QUERY
  SELECT 
    'invalid_status'::text,
    COUNT(*)::bigint,
    'Invalid status values found (not pending, running, completed, or failed)'::text
  FROM sync_status 
  WHERE status NOT IN ('pending', 'running', 'completed', 'failed');
  
  -- Check for missing required fields
  RETURN QUERY
  SELECT 
    'missing_required_fields'::text,
    COUNT(*)::bigint,
    'Records with missing sync_id, status, or start_time'::text
  FROM sync_status 
  WHERE sync_id IS NULL 
     OR status IS NULL 
     OR start_time IS NULL;
     
  -- Check for completed/failed syncs without end_time
  RETURN QUERY
  SELECT 
    'missing_end_time'::text,
    COUNT(*)::bigint,
    'Completed or failed syncs without end_time'::text
  FROM sync_status 
  WHERE status IN ('completed', 'failed') 
     AND end_time IS NULL;
     
  -- Check for syncs with end_time before start_time
  RETURN QUERY
  SELECT 
    'invalid_time_order'::text,
    COUNT(*)::bigint,
    'Syncs with end_time before start_time'::text
  FROM sync_status 
  WHERE end_time IS NOT NULL 
     AND end_time < start_time;
     
  -- Check for long-running syncs (>1 hour)
  RETURN QUERY
  SELECT 
    'long_running_syncs'::text,
    COUNT(*)::bigint,
    'Syncs running for more than 1 hour (possible stuck processes)'::text
  FROM sync_status 
  WHERE status = 'running' 
     AND start_time < NOW() - INTERVAL '1 hour';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permissions to service role
GRANT EXECUTE ON FUNCTION validate_sync_status_data() TO service_role;

-- =============================================================================
-- SCHEMA VERSION UPDATE
-- =============================================================================

-- Update schema version record
INSERT INTO schema_versions (version, description) VALUES
('2.3.0', 'Sync status monitoring schema with comprehensive tracking and validation functions')
ON CONFLICT (version) DO NOTHING;

-- =============================================================================
-- VALIDATION QUERIES
-- =============================================================================

-- Verify sync_status table was created successfully
DO $$
BEGIN
  -- Check table exists
  ASSERT (SELECT COUNT(*) FROM information_schema.tables 
          WHERE table_name = 'sync_status') = 1,
          'Sync_status table was not created';
          
  -- Check required columns exist
  ASSERT (SELECT COUNT(*) FROM information_schema.columns 
          WHERE table_name = 'sync_status' 
          AND column_name IN ('sync_id', 'status', 'start_time', 'records_processed', 'errors')) = 5,
          'Required columns missing from sync_status table';
          
  -- Check unique constraints exist
  ASSERT (SELECT COUNT(*) FROM information_schema.table_constraints 
          WHERE table_name = 'sync_status' 
          AND constraint_type = 'UNIQUE') >= 1,
          'Unique constraints missing from sync_status table';
          
  -- Check indexes were created
  ASSERT (SELECT COUNT(*) FROM pg_indexes 
          WHERE tablename = 'sync_status') >= 5,
          'Required indexes missing from sync_status table';
          
  -- Check RLS is enabled
  ASSERT (SELECT relrowsecurity FROM pg_class WHERE relname = 'sync_status') = true,
          'Row Level Security not enabled on sync_status table';
          
  -- Check trigger exists
  ASSERT (SELECT COUNT(*) FROM information_schema.triggers 
          WHERE event_object_table = 'sync_status' 
          AND trigger_name = 'update_sync_status_timestamp_trigger') = 1,
          'Timestamp trigger missing from sync_status table';
          
  RAISE NOTICE 'Sync status schema migration completed successfully';
END $$;